cooks/urls.py
from django.urls import path
from . import views as cook_views


urlpatterns = [
    path('register/', cook_views.register_cook, name='register'),
    path('register/welcome', cook_views.cook_profile, name='welcome'),
    path('makeplan', cook_views.make_plan.as_view(), name='make-plan'),
    path('viewplans', cook_views.view_plans, name='view-plans'),
    path('viewplans/<int:plan_id>', cook_views.view_plan, name='view-plan'),
    path('viewplans/<int:plan_id>/<int:review>/<str:meal_id>',
         cook_views.view_plan, name='view-plan-vote'),
    path('mod_list/<int:plan_id>', cook_views.view_plan, name='mod-list'),
    path('shp_list/<int:plan_id>', cook_views.list_idx, name='shop-list'),
    path('shp_list/<int:plan_id>/<int:item_id>/<int:direction>',
         cook_views.shp_got, name='chg-list-item'),
    path('idx_list/<int:plan_id>', cook_views.list_idx, name='list-idx'),
    path('idx_list/<int:plan_id>/<int:shp>', cook_views.list_idx,
         name='list-idx-shp'),
    path('add_list/<int:plan_id>/<str:meal_id>',
         cook_views.list_add, name='add-list-item'),
    path('edit_list/<int:plan_id>/<int:plan_itm_id>',
         cook_views.list_add, name='edit-list-item'),
    path('del_list/<int:plan_id>/<int:id>',
         cook_views.list_del, name='del-list-item'),
    path('mod_plan/<int:plan_id>', cook_views.add_to_plan, name='add_to_plan'),
    path('mod_plan/<int:plan_id>/<str:meal_id>', cook_views.add_meal_to_plan,
         name='add_meal_to_plan'),
    path('del_meal_from_plan/<int:plan_id>/<str:meal_id>',
         cook_views.del_meal_from_plan, name='del_meal_from_plan'),
    path('del_plan/<int:plan_id>', cook_views.del_plan, name='del_plan')
    ]

mealcurator/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, BlogSitemap, AIRecipesSitemap

sitemaps = {'static': StaticViewSitemap, 'blog': BlogSitemap, 'ai': AIRecipesSitemap}

urlpatterns = [
    path('', include('meals.urls')),
    path('meals/', include('meals.urls')),
    path('admin/', admin.site.urls),
    path('register/', include('cooks.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cooks/', include('cooks.urls')),
    path('share/', include('stewpot.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

meals/urls.py
from django.urls import path
from meals import views


urlpatterns = [
    path('', views.index, name='index'),
    path('submit', views.get_recipe.as_view(), name='get-recipe'),
    path('browse', views.show_recipe, name='view-recipes'),
    path('howto', views.howto, name='howto'),
    path('about', views.about, name='about'),
    path('changelog', views.change_log, name='change_log'),
    path('attribution', views.creative_commons_credit, name='ccc'),
    path('mstr', views.mstr_lst, name='view-mstr-list'),
    path('mstr/<str:meal_id>', views.mstr_lst_idx, name='edit-mstr-list'),
    path('mstr/<str:meal_id>/add', views.mstr_lst_add, name='add-list-item-meal'),
    path('mstr/<str:meal_id>/<int:item_id>', views.mstr_lst_del,
         name='del-list-item-meal'),
]

meals/models.py
from fractions import Fraction
import requests
import random
from bs4 import BeautifulSoup
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import uuid
from django.db import models
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from mealcurator import choices


class raw_recipe(models.Model):
    title = models.CharField('Recipe Title', max_length=255)
    rec_url = models.URLField('Recpie URL', unique=True)
    vegan = models.BooleanField('Vegan')
    vegetarian = models.BooleanField('Vegetarian')
    meal_time = models.CharField('Meal Type',
                                 max_length=2,
                                 choices=choices.meal_time_choices)
    dish_type = models.CharField('Dish Type',
                                 max_length=2,
                                 choices=choices.dish_type_choices)
    protein_type = models.CharField('Main Protein',
                                    max_length=2,
                                    choices=choices.protein_choices,
                                    default='na')
    cooking_method = models.CharField('Cooking Method',
                                      max_length=2,
                                      choices=choices.cooking_method_choices)
    cooking_time = models.CharField('Cooking Time',
                                    max_length=2,
                                    choices=choices.cook_time_choices)
    mstr_flag = models.BooleanField(default=False)
    error_flag = models.BooleanField(default=False)
    ai_recipe = models.BooleanField('AImade', default=False)

    def __str__(self):
        return self.rec_url

    def pull_mstr(self):
        try:
            self.soup = self._make_soup()
            title = self.soup.title.string
            learned_tkns, words = self._make_tkns()
            mstr = mstr_recipe.objects.create(
                    meal_id=uuid.uuid1(),
                    title=title,
                    rec_url=self.rec_url,
                    vegan=self.vegan,
                    vegetarian=self.vegetarian,
                    meal_time=self.meal_time,
                    dish_type=self.dish_type,
                    cooking_method=self.cooking_method,
                    cooking_time=self.cooking_time,
                    protein_type=self.protein_type,
                    found_words=learned_tkns,
                    ai_recipe=self.ai_recipe
                   )
            mstr_search.objects.create(
                meal_id=mstr,
                raw_words=words
            )
            return True

        except ValueError:
            return False

    def _make_soup(self):
        user_agents = [
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36', 
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36', 
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36', 
            'Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148', 
            'Mozilla/5.0 (Linux; Android 11; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Mobile Safari/537.36' 
        ]
        user_agent = random.choice(user_agents)
        headers = {'User-Agent': user_agent}
        page = requests.get(self.rec_url, headers=headers)
        if not page.ok:
            raise ValueError(f'URL did not resolve to OK: {page.status_code}')
        return BeautifulSoup(page.content, 'html.parser')

    def _make_tkns(self):
        # Returns JSON represtnation of lemented word list
        words = [w for w in word_tokenize(self.soup.get_text().lower())
                 if w.isalpha()]
        raw_tkns = [w for w in words
                    if w not in stopwords.words('english')]
        lemmatizer = WordNetLemmatizer()
        lemented = [lemmatizer.lemmatize(w) for w in raw_tkns]
        return lemented, words

    class Meta:
        indexes = [
            models.Index(fields=['mstr_flag', 'error_flag'])
        ]


class meal_item(models.Model):
    item_name = models.CharField('Item Name', max_length=255)
    item_location = models.CharField('Item Section',
                                     max_length=2,
                                     choices=choices.sections,
                                     default='un')
    poss_duplicate = models.BooleanField('Possible Duplicate', default=False)

    def __str__(self):
        return self.item_name


class mstr_recipe(models.Model):
    meal_id = models.UUIDField(primary_key=True,
                               editable=False)
    title = models.CharField('Recipe Title', max_length=255)
    rec_url = models.URLField('Recipe URL')
    vegan = models.BooleanField('Vegan')
    vegetarian = models.BooleanField('Vegetarian')
    meal_time = models.CharField('Meal Type',
                                 max_length=2,
                                 choices=choices.meal_time_choices)
    dish_type = models.CharField('Dish Type',
                                 max_length=2,
                                 choices=choices.dish_type_choices)
    cooking_method = models.CharField('Cooking Method',
                                      max_length=2,
                                      choices=choices.cooking_method_choices)
    cooking_time = models.CharField('Cooking Time',
                                    max_length=2,
                                    choices=choices.cook_time_choices)
    protein_type = models.CharField('Main Protein',
                                    max_length=2,
                                    choices=choices.protein_choices,
                                    default='na')
    ai_recipe = models.BooleanField('AImade', default=False)
    times_selected = models.PositiveIntegerField('Number of times Selected',
                                                 default=0)
    sumreview = models.PositiveIntegerField('Sum of Reviews',
                                            default=0)
    numreview = models.PositiveIntegerField('Number of Reviews',
                                            default=0)
    dummy = models.BooleanField(default=False, null=True)
    # TODO: Make this into another model vs tagging along here
    words = models.JSONField('Found Words', name='found_words', default=None)

    def __str__(self):
        return self.title

    def avg_review(self):
        if self.numreview == 0:
            return 0
        else:
            review = Fraction(self.sumreview/self.numreview).limit_denominator(2)
            return float(review)


class mstr_search(models.Model):
    meal_id = models.OneToOneField(mstr_recipe, on_delete=models.CASCADE,
                                   primary_key=True)
    raw_words = models.TextField('Recipe Text')
    search_vector = SearchVectorField(null=True)

    class Meta:
        indexes = [GinIndex(fields=['search_vector'])]


class mstr_recipe_list(models.Model):
    meal = models.ForeignKey(mstr_recipe, on_delete=models.CASCADE)
    item = models.ForeignKey(meal_item, on_delete=models.CASCADE)
    qty = models.DecimalField(default=1, max_digits=8, decimal_places=3)
    uom = models.CharField('Unit of Measure', max_length=2,
                           choices=choices.uoms,
                           default='qt')

    class Meta:
        unique_together = ['meal', 'item']


class recipe_sims(models.Model):
    sim = models.ForeignKey(mstr_recipe, on_delete=models.CASCADE)
    compare = models.ForeignKey(mstr_recipe, on_delete=models.CASCADE,
                                related_name='compare_meal')
    score = models.DecimalField('Simularity Score', 'sim_score', 10, 10)
    affirmed_votes = models.PositiveIntegerField('Agreement Votes', 'agree',
                                                 default=0)
    disagree_votes = models.PositiveIntegerField('Disagreement Votes',
                                                 'disagree', default=0)


class change_log(models.Model):
    version = models.CharField('Version', max_length=256, primary_key=True)
    implemented = models.DateField()

    def __str__(self):
        return self.version


class changes(models.Model):
    version = models.ForeignKey(change_log, on_delete=models.CASCADE)
    change = models.CharField('Change Type', max_length=2,
                              choices=choices.change)
    change_desc = models.CharField('Change Description', max_length=256)
    entry_date = models.DateField(auto_now_add=True)


class creative_commons(models.Model):
    title = models.CharField(max_length=256)
    internal = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    link_text = models.CharField(max_length=256)
    link = models.URLField()

    def __str__(self):
        return self.title

templates/meals/mstr_lst.html
{% extends "base.html" %}
{% load static %}
{% load cooks_extras %}
{% block css_style %}






{% endblock css_style %}

{% block page_content %}

{% if idx %}
<h2>{{ meal.title }}</h2>
<h4><a href="{{ meal.rec_url }}" target="_blank">Link to Recipe</a></h4>




<div class="list">
    <table>
      <th colspan="2">Quantity</th>
      <th>Unit</th>
      <th>Item</th>

      <tr><form action="{% url 'add-list-item-meal' meal_id=meal_id %}", method="post">{% csrf_token %}
        <td> 
           <input type='number' style='width: 40px;' name ='item-qty' value="0" min="0" max="1000"> </td>
           <td>
            <select style='width: 45px;' name ='item-qty-dec'>
              <option value="%"> --- </option>
              <option value="1/8"> 1/8 </option>
              <option value="1/4"> 1/4 </option>
              <option value="1/3"> 1/3 </option>
              <option value="1/2"> 1/2 </option>
              <option value="2/3"> 2/3 </option>
              <option value="3/4"> 3/4 </option>
            </td>
        <td>
          <select style='width: 70px' name='item-uom'>
          {% for key, value in uoms %}
            <option value="{{ key }}">{{ value }}</option>
          {% endfor %}
          </select></td>
        <td>
            <input list="new_items" style='width: 200px;' name='new-item'>
            <datalist id="new_items">
              {% for poss_item in items_search %}
              {% if poss_item.id != 1 %}
            <option value="{{ poss_item | title }}"></option>
              {% endif %}
              {% endfor %}
            </datalist>
          
          </td>
            <td><button type="submit" value="Add"><img src="{% static 'images/file-plus.svg' %}" alt="File wit add symbol" title="Add item to list" height="14"></button></td></tr></form>     
      
      {% for item in items %}
      <tr>
        <td colspan="2"> {{ item.qty | dec_cleaner }}</td>
        <td>{{ item.uom | choice_finder:"uoms" }}</td>
        <td>{{ item.item__item_name | title }}</td>
        <td><a href="{% url 'del-list-item-meal' meal_id=meal_id item_id=item.item_id %}"> <img src="{% static 'images/trash-2.svg' %}" alt="Trash Can" title="Remove {{ item.item__item_name }} from list" height="18"></a></td>
      </tr>
      {% endfor %}
    </table>
    <h3><a href="{% url 'view-mstr-list' %}">Return to Recipe Lists</a></h3>
 
</div>










{% else %}
{% for meal in meals %}
<p>
<a href="{% url 'edit-mstr-list' meal.meal_id%}">{{ meal.title }}</a> number items {{ meal.num_items }}
</p>
{% endfor %}
{% endif %}
{% endblock page_content %}

templates/meals/showmeals.html
{% extends "base.html" %}
{% load static %}
{% load cooks_extras %}
{% block css_style %}

.resultTbl {
    width: 90%;
    max-width: 1100px;
    display: flex;
    flex-flow: row wrap;
    justify-content: space-evenly;
    align-content: space-around;
    margin: auto;
}

.searchinput {
    margin: auto;
    text-align: center;

}

.navicontbl {
    width: 340px;
    border-spacing: 5px;
}

{% endblock css_style %}

{% block page_content %}

{% if plan_view %}
<h1>Recipes in: {{ mp.name }}</h1>
<div class="navicons">
    <table class="navicontbl">
    <tr>
      <td><a href="{% url 'add_to_plan' mp.id %}">
        <img src="{% static 'images/find-recipes.svg' %}" height="80" width="80" alt="Image of searching for recipes" title="Add more recipes to this meal plan">
            <br>Add More Recipes to Plan</a></td>
      <td><a href="{% url 'mod-list' mp.id %}">
        <img src="{% static 'images/make-list.svg' %}" height="80" width="80" alt="Image of an in process list and pencil" title="Make/Edit the list for this meal plan">
            <br>Make/Edit Shopping List</a></td>
      <td><a href="{% url 'shop-list' mp.id %}">
        <img src="{% static 'images/shop-list.svg' %}" height="80" width="80" alt="Image of a shopping list being checked off" title="View shopping list for this meal plan">
            <br>View Shopping List</a></td>
    </tr>
   </table>
</div>
{% elif add_to_plan_view %}
<h1>Browsing Recipes for: {{ mp.name }}</h1> 
{% else %}
<h1>Browse Recipes</h1>
{% endif %}



{% if add_to_plan_view %}
<div class="searchinput"> 
    <form action="{% url 'add_to_plan' mp.id %}">
    <select name="meal_time">
        {% if request.GET.meal_time and request.GET.meal_time != '%' %}
        <option value={{ request.GET.meal_time }}>{{ meal_time | val_ret_lstp:request.GET.meal_time }}</option>
        {% endif %}
        <option value="%">-- All Meal Times --</option>
        {% for key, value in meal_time %}
            {% if key != request.GET.meal_time %}
        <option value="{{ key }}">{{ value }}</option>    
            {% endif %}
        {% endfor %}
    </select>

    <Select name="cooking_time">
        {% if request.GET.cooking_time and request.GET.cooking_time != '%' %}
        <option value={{ request.GET.cooking_time }}>{{ cooking_time | val_ret_lstp:request.GET.cooking_time }}</option>
        {% endif %}
        <option value="%">-- All Cooking Times --</option>
        {% for key, value in cooking_time %}
            {% if key != request.GET.cooking_time %}
            <option value="{{ key }}">{{ value }}</option>    
            {% endif %}
        {% endfor %}
    </Select>

    <Select name="cooking_method">
        {% if request.GET.cooking_method and request.GET.cooking_method != '%' %}
        <option value={{ request.GET.cooking_method }}>{{ cooking_method | val_ret_lstp:request.GET.cooking_method }}</option>
        {% endif %}
        <option value="%">-- All Cooking Methods --</option>
        {% for key, value in cooking_method %}
            {% if key != request.GET.cooking_method %}
            <option value="{{ key }}">{{ value }}</option>    
            {% endif %}
        {% endfor %}
    </Select>

    <Select name="protein_type">
        {% if request.GET.protein_type and request.GET.protein_type != '%' %}
        <option value={{ request.GET.protein_type }}>{{ protein_choices | val_ret_lstp:request.GET.protein_type }}</option>
        {% endif %}       
        <option value="%">-- All Main Proteins --</option>
        {% for key, value in protein_choices %}
            {% if key != request.GET.protein_type %}        
            <option value="{{ key }}">{{ value }}</option>
            {% endif %}
        {% endfor %}
    </Select>

    <Select name="dish_type">
        {% if request.GET.dish_type and request.GET.dish_type != '%' %}
        <option value={{ request.GET.dish_type }}>{{ dish_type | val_ret_lstp:request.GET.dish_type }}</option>
        {% endif %}  
        <option value="%">-- All Dish Types --</option>
        {% for key, value in dish_type %}
            {% if key != request.GET.dish_type %}     
            <option value="{{ key }}">{{ value }}</option>    
            {% endif %}
        {% endfor %}
    </Select>
    <br><br>
<input type="search" name="q" placeholder="Search by free-text..."/>
<input type="submit" value="Search"/>
</form>
{% if user.is_staff %}
<br><strong><a href="{% url 'ai-recipe-start' %}">Build a recipe with AI</a></strong>
{% endif %}
</div>
<h3><a href="{% url 'view-plan' mp.id %}">Back to {{ mp.name }} Overview</a></h3>
{% endif %}
<hr/>


<div class="resultTbl">
    {% for meal in meals %}
    {% if not meal.meal__dummy %}
        <div class=recCard>
            <table>
                <th colspan=2><a href="{% if plan_view %}{{ meal.meal__rec_url }}{% else %}{{ meal.rec_url }}{% endif %}", target="_blank">{% if plan_view %}{{ meal.meal__title }}{% else %}{{ meal.title }}{% endif %}</a></th>
                <tr>
                <td colspan=2>
                {% if plan_view %}
                
                {% include "meals/ranking.html" with rank=meal.review meal_id=meal.meal_id plan_id=mp.id plan_view=plan_view %}    
                {% else %}
                {% include "meals/ranking.html" with rank=meal.avg_review only %}
                {% endif %}    
            </td></tr>
            <tr><td><b>Vegan:</b> {% if plan_view %}{{ meal.meal__vegan|yesno:"Yes,No" }}{% else %}{{ meal.vegan|yesno:"Yes,No" }}{% endif %}</td><td><b>Vegetarian:</b> {% if plan_view %}{{ meal.meal__vegetarian|yesno:"Yes,No" }}{% else %}{{ meal.vegetarian|yesno:"Yes,No" }}{% endif %}</td></tr>
            <tr><td class="leftTd">Meal Time:</td>
                <td class="rightTd">
                {% if plan_view %}    
                    {% if meal.meal__meal_time == 'bk' %}  Breakfast
                    {% elif meal.meal__meal_time == 'lu' %}  Lunch 
                    {% elif meal.meal__meal_time == 'di' %}  Dinner 
                    {% elif meal.meal__meal_time == 'sd' %}  Side Dish 
                    {% elif meal.meal__meal_time == 'de' %}  Dessert
                    {% elif meal.meal__meal_time == 'sn' %}  Snack         
                    {% endif %}
                {% else %}
                {{ meal.get_meal_time_display }}
                {% endif %}
            </td></tr>
            <tr><td class="leftTd">Cooking Time:</td>
                <td class="rightTd">
                {% if plan_view %}
                    {% if meal.meal__cooking_time == '20' %}  Less than 20 Minutes
                    {% elif meal.meal__cooking_time == '40' %}  20 to 40 Minutes
                    {% elif meal.meal__cooking_time == '60' %}  40 to 60 Minutes
                    {% elif meal.meal__cooking_time == '61' %}  Over 60 Minutes
                    {% endif %}
                {% else %}
                {{ meal.get_cooking_time_display }}
                {% endif %}
            </td></tr>
            <tr><td class="leftTd">Method:</td>
                <td class="rightTd">
                {% if plan_view %}
                    {% if meal.meal__cooking_method == 'st' %}  Stove Top
                    {% elif meal.meal__cooking_method == 'mi' %}  Microwave 
                    {% elif meal.meal__cooking_method == 'bl' %}  Blender 
                    {% elif meal.meal__cooking_method == 'gr' %}  Grill 
                    {% elif meal.meal__cooking_method == 'ov' %}  Oven 
                    {% elif meal.meal__cooking_method == 'pr' %}  Pressure Cooker 
                    {% elif meal.meal__cooking_method == 'sc' %}  Slow Cooker 
                    {% elif meal.meal__cooking_method == 'af' %}  Air Fryer 
                    {% elif meal.meal__cooking_method == 'ra' %}  Raw/Uncooked 
                    {% endif %}
                {% else %}
                {{ meal.get_cooking_method_display }}
                {% endif %}
            </td></tr>
            <tr><td class="leftTd">Dish Type:</td>
                <td class="rightTd">
                {% if plan_view %}
                    {% if meal.meal__dish_type == 'sp' %}  Soup
                    {% elif meal.meal__dish_type == 'bk' %}  Baked Dish
                    {% elif meal.meal__dish_type == 'pa' %}  Pasta
                    {% elif meal.meal__dish_type == 'cu' %}  Curry 
                    {% elif meal.meal__dish_type == 'ca' %}  Casserole
                    {% elif meal.meal__dish_type == 'st' %}  Stew
                    {% elif meal.meal__dish_type == 'sa' %}  Salad
                    {% elif meal.meal__dish_type == 'lt' %}  Light Dish
                    {% elif meal.meal__dish_type == 'sm' %}  Smoothie 
                    {% elif meal.meal__dish_type == 'na' %}  Other
                    {% endif %}
                {% else %}
                {{ meal.get_dish_type_display }}
                {% endif %}
                </td></tr>
                <tr><td class="leftTd">Protein Type:</td>
                    <td class="rightTd">
                    {% if plan_view %}
                        {% if meal.meal__protein_type == 'be' %}  Beef
                        {% elif meal.meal__protein_type == 'ch' %}  Chicken
                        {% elif meal.meal__protein_type == 'pb' %}  Plant Based
                        {% elif meal.meal__protein_type == 'se' %}  Fish / Shellfish 
                        {% elif meal.meal__protein_type == 'pk' %}  Pork
                        {% elif meal.meal__protein_type == 'na' %}  None
                        {% elif meal.meal__protein_type == 'ot' %}  Other
                        {% endif %}
                    {% else %}
                    {{ meal.get_protein_type_display }}
                    {% endif %}
                </td></tr>
            <tr><td><a href="{% if plan_view %}{{ meal.meal__rec_url }}{% else %}{{ meal.rec_url }}{% endif %}", target="_blank"><img src="{% static 'images/book-open.svg' %}" alt="Open Book" title="Open Recipe in New Tab"></a></td>
                <td>
                {% if plan_view %}
                <!--TODO: Center the buttons-->
                <a href="{% url 'start-shared' meal.meal_id %}"><img src="{% static 'images/share.svg' %}" alt="Share Icon" title="Share this recipe"></a></td>
                <td><a href="{% url 'del_meal_from_plan' mp.id meal.meal_id %}"><img src="{% static 'images/trash-2.svg' %}" alt="Trash Can" title="Remove from Meal Plan"></a>
                {% elif add_to_plan_view %}
                <a href="{% url 'add_meal_to_plan' mp.id meal.meal_id %}"><img src="{% static 'images/file-plus.svg' %}" alt="File with add sign" tite="Add Recipe to Meal Plan"></a>
                {% endif %}
                </td></tr>
            </table>
            <br>
            <br>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% if plan_view %}
<h4><a href="{% url 'del_plan' mp.id %}">Delete this Plan</a></h4>
{% endif %}

{% endblock page_content %}